// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories_players.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addPlayerToCategory = `-- name: AddPlayerToCategory :exec
INSERT INTO categories_players (category_id, player_id)
VALUES ($1, $2)
ON CONFLICT (category_id, player_id) DO NOTHING
`

type AddPlayerToCategoryParams struct {
	CategoryID uuid.UUID
	PlayerID   uuid.UUID
}

func (q *Queries) AddPlayerToCategory(ctx context.Context, arg AddPlayerToCategoryParams) error {
	_, err := q.db.ExecContext(ctx, addPlayerToCategory, arg.CategoryID, arg.PlayerID)
	return err
}

const addPlayersToCategoryBulk = `-- name: AddPlayersToCategoryBulk :exec
INSERT INTO categories_players (category_id, player_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT (category_id, player_id) DO NOTHING
`

type AddPlayersToCategoryBulkParams struct {
	CategoryID uuid.UUID
	PlayerIds  []uuid.UUID
}

func (q *Queries) AddPlayersToCategoryBulk(ctx context.Context, arg AddPlayersToCategoryBulkParams) error {
	_, err := q.db.ExecContext(ctx, addPlayersToCategoryBulk, arg.CategoryID, pq.Array(arg.PlayerIds))
	return err
}

const listPlayersInCategory = `-- name: ListPlayersInCategory :many
SELECT p.id, p.nickname, p.name, p.team_name, p.country_code, p.city, p.profile_picture_url, p.created_at, p.modified_at
FROM players p
JOIN categories_players cp ON p.id = cp.player_id
WHERE cp.category_id = $1
`

func (q *Queries) ListPlayersInCategory(ctx context.Context, categoryID uuid.UUID) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, listPlayersInCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Nickname,
			&i.Name,
			&i.TeamName,
			&i.CountryCode,
			&i.City,
			&i.ProfilePictureUrl,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePlayerFromCategory = `-- name: RemovePlayerFromCategory :exec
DELETE FROM categories_players
WHERE category_id = $1 AND player_id = $2
`

type RemovePlayerFromCategoryParams struct {
	CategoryID uuid.UUID
	PlayerID   uuid.UUID
}

func (q *Queries) RemovePlayerFromCategory(ctx context.Context, arg RemovePlayerFromCategoryParams) error {
	_, err := q.db.ExecContext(ctx, removePlayerFromCategory, arg.CategoryID, arg.PlayerID)
	return err
}
