// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, name, tournament_id)
VALUES (
    gen_random_uuid(),
    $1,
    $2
)
RETURNING id, name, tournament_id
`

type CreateCategoryParams struct {
	Name         string
	TournamentID uuid.UUID
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.Name, arg.TournamentID)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.TournamentID)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, tournament_id
FROM categories
WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.TournamentID)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, tournament_id
FROM categories
WHERE tournament_id = $1
`

func (q *Queries) ListCategories(ctx context.Context, tournamentID uuid.UUID) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.TournamentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
    name = COALESCE($2, name)
WHERE id = $1
RETURNING id, name, tournament_id
`

type UpdateCategoryParams struct {
	ID   uuid.UUID
	Name sql.NullString
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory, arg.ID, arg.Name)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.TournamentID)
	return i, err
}

const validateCategoryBelongsToTournament = `-- name: ValidateCategoryBelongsToTournament :one
SELECT id
FROM categories
WHERE id = $1 AND tournament_id = $2
`

type ValidateCategoryBelongsToTournamentParams struct {
	ID           uuid.UUID
	TournamentID uuid.UUID
}

func (q *Queries) ValidateCategoryBelongsToTournament(ctx context.Context, arg ValidateCategoryBelongsToTournamentParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, validateCategoryBelongsToTournament, arg.ID, arg.TournamentID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
