// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: charts.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createChart = `-- name: CreateChart :one
INSERT INTO charts (
    id,
    song_id,
    mode,
    level,
    player_count
)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4
)
RETURNING id, song_id, mode, level, player_count
`

type CreateChartParams struct {
	SongID      uuid.UUID
	Mode        int32
	Level       int32
	PlayerCount int32
}

func (q *Queries) CreateChart(ctx context.Context, arg CreateChartParams) (Chart, error) {
	row := q.db.QueryRowContext(ctx, createChart,
		arg.SongID,
		arg.Mode,
		arg.Level,
		arg.PlayerCount,
	)
	var i Chart
	err := row.Scan(
		&i.ID,
		&i.SongID,
		&i.Mode,
		&i.Level,
		&i.PlayerCount,
	)
	return i, err
}

const deleteChart = `-- name: DeleteChart :exec
DELETE FROM charts
WHERE id = $1
`

func (q *Queries) DeleteChart(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChart, id)
	return err
}

const getChart = `-- name: GetChart :one
SELECT id, song_id, mode, level, player_count
FROM charts
WHERE id = $1
`

func (q *Queries) GetChart(ctx context.Context, id uuid.UUID) (Chart, error) {
	row := q.db.QueryRowContext(ctx, getChart, id)
	var i Chart
	err := row.Scan(
		&i.ID,
		&i.SongID,
		&i.Mode,
		&i.Level,
		&i.PlayerCount,
	)
	return i, err
}

const listCharts = `-- name: ListCharts :many
SELECT id, song_id, mode, level, player_count
FROM charts
ORDER BY song_id ASC
`

func (q *Queries) ListCharts(ctx context.Context) ([]Chart, error) {
	rows, err := q.db.QueryContext(ctx, listCharts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chart
	for rows.Next() {
		var i Chart
		if err := rows.Scan(
			&i.ID,
			&i.SongID,
			&i.Mode,
			&i.Level,
			&i.PlayerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChart = `-- name: UpdateChart :one
UPDATE charts
SET
    song_id = COALESCE($2, song_id),
    mode = COALESCE($3, mode),
    level = COALESCE($4, level),
    player_count = COALESCE($5, player_count)
WHERE id = $1
RETURNING id, song_id, mode, level, player_count
`

type UpdateChartParams struct {
	ID          uuid.UUID
	SongID      uuid.NullUUID
	Mode        sql.NullInt32
	Level       sql.NullInt32
	PlayerCount sql.NullInt32
}

func (q *Queries) UpdateChart(ctx context.Context, arg UpdateChartParams) (Chart, error) {
	row := q.db.QueryRowContext(ctx, updateChart,
		arg.ID,
		arg.SongID,
		arg.Mode,
		arg.Level,
		arg.PlayerCount,
	)
	var i Chart
	err := row.Scan(
		&i.ID,
		&i.SongID,
		&i.Mode,
		&i.Level,
		&i.PlayerCount,
	)
	return i, err
}
