// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type Grade string

const (
	GradeF    Grade = "F"
	GradeD    Grade = "D"
	GradeC    Grade = "C"
	GradeB    Grade = "B"
	GradeA    Grade = "A"
	GradeAP   Grade = "A_P"
	GradeAA   Grade = "AA"
	GradeAAP  Grade = "AA_P"
	GradeAAA  Grade = "AAA"
	GradeAAAP Grade = "AAA_P"
	GradeS    Grade = "S"
	GradeSP   Grade = "S_P"
	GradeSS   Grade = "SS"
	GradeSSP  Grade = "SS_P"
	GradeSSS  Grade = "SSS"
	GradeSSSP Grade = "SSS_P"
)

func (e *Grade) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Grade(s)
	case string:
		*e = Grade(s)
	default:
		return fmt.Errorf("unsupported scan type for Grade: %T", src)
	}
	return nil
}

type NullGrade struct {
	Grade Grade
	Valid bool // Valid is true if Grade is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGrade) Scan(value interface{}) error {
	if value == nil {
		ns.Grade, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Grade.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGrade) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Grade), nil
}

type RoundState string

const (
	RoundStateNotStarted RoundState = "not_started"
	RoundStateInProgress RoundState = "in_progress"
	RoundStatePaused     RoundState = "paused"
	RoundStateFinished   RoundState = "finished"
)

func (e *RoundState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoundState(s)
	case string:
		*e = RoundState(s)
	default:
		return fmt.Errorf("unsupported scan type for RoundState: %T", src)
	}
	return nil
}

type NullRoundState struct {
	RoundState RoundState
	Valid      bool // Valid is true if RoundState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoundState) Scan(value interface{}) error {
	if value == nil {
		ns.RoundState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoundState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoundState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoundState), nil
}

type CategoriesPlayer struct {
	CategoryID uuid.UUID
	PlayerID   uuid.UUID
}

type Category struct {
	ID           uuid.UUID
	Name         string
	TournamentID uuid.UUID
}

type Chart struct {
	ID          uuid.UUID
	SongID      uuid.UUID
	Mode        int32
	Level       int32
	PlayerCount int32
}

type ChartsWithSong struct {
	ChartID      uuid.UUID
	Mode         int32
	Level        int32
	PlayerCount  int32
	SongID       uuid.UUID
	SongName     string
	SongTitleUrl sql.NullString
}

type Player struct {
	ID                uuid.UUID
	Nickname          string
	Name              sql.NullString
	TeamName          sql.NullString
	CountryCode       sql.NullString
	City              sql.NullString
	ProfilePictureUrl sql.NullString
	CreatedAt         time.Time
	ModifiedAt        time.Time
}

type Round struct {
	ID              uuid.UUID
	Name            sql.NullString
	Format          int32
	Levels          sql.NullString
	QualifiersCount int32
	CategoryID      uuid.UUID
	OrderIndex      int32
	CurrentState    RoundState
}

type RoundsChart struct {
	RoundID    uuid.UUID
	ChartID    uuid.UUID
	OrderIndex int32
}

type RoundsPlayer struct {
	RoundID    uuid.UUID
	PlayerID   uuid.UUID
	OrderIndex int32
}

type Score struct {
	ID        uuid.UUID
	RoundID   uuid.UUID
	PlayerID  uuid.UUID
	ChartID   uuid.UUID
	Score     int32
	Perfect   sql.NullInt32
	Great     sql.NullInt32
	Good      sql.NullInt32
	Bad       sql.NullInt32
	Miss      sql.NullInt32
	MaxCombo  sql.NullInt32
	Kcal      sql.NullFloat64
	Grade     NullGrade
	StagePass sql.NullBool
	VideoUrl  sql.NullString
}

type Song struct {
	ID       uuid.UUID
	Name     string
	TitleUrl sql.NullString
}

type Tournament struct {
	ID        uuid.UUID
	Name      string
	Location  sql.NullString
	StartDate sql.NullTime
}
