// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Player struct {
	ID                uuid.UUID
	Nickname          string
	Name              sql.NullString
	TeamName          sql.NullString
	CountryCode       sql.NullString
	City              sql.NullString
	ProfilePictureUrl sql.NullString
	CreatedAt         time.Time
	ModifiedAt        time.Time
}
