// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package database

import (
	"context"
	"database/sql"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (id, nickname, name, team_name, country_code, city, created_at, modified_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    NOW(),
    NOW()
)
RETURNING id, nickname, name, team_name, country_code, city, profile_picture_url, created_at, modified_at
`

type CreatePlayerParams struct {
	Nickname    string
	Name        sql.NullString
	TeamName    sql.NullString
	CountryCode sql.NullString
	City        sql.NullString
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, createPlayer,
		arg.Nickname,
		arg.Name,
		arg.TeamName,
		arg.CountryCode,
		arg.City,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Name,
		&i.TeamName,
		&i.CountryCode,
		&i.City,
		&i.ProfilePictureUrl,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const listPlayers = `-- name: ListPlayers :many
SELECT id, nickname, name, team_name, country_code, city, profile_picture_url, created_at, modified_at
FROM players
ORDER BY created_at DESC
`

func (q *Queries) ListPlayers(ctx context.Context) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, listPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Nickname,
			&i.Name,
			&i.TeamName,
			&i.CountryCode,
			&i.City,
			&i.ProfilePictureUrl,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
