// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package database

import (
	"context"
	"database/sql"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (id, nickname, name, team_name, country_code, city, created_at, modified_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    NOW(),
    NOW()
)
RETURNING id, nickname, name, team_name, country_code, city, profile_picture_url, created_at, modified_at
`

type CreatePlayerParams struct {
	Nickname    string
	Name        sql.NullString
	TeamName    sql.NullString
	CountryCode sql.NullString
	City        sql.NullString
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, createPlayer,
		arg.Nickname,
		arg.Name,
		arg.TeamName,
		arg.CountryCode,
		arg.City,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Name,
		&i.TeamName,
		&i.CountryCode,
		&i.City,
		&i.ProfilePictureUrl,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
