// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rounds.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const cancelRoundStart = `-- name: CancelRoundStart :exec
UPDATE rounds
SET current_state = 'not_started'
WHERE id = $1 AND current_state = 'in_progress'
`

func (q *Queries) CancelRoundStart(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, cancelRoundStart, id)
	return err
}

const createRound = `-- name: CreateRound :one
INSERT INTO rounds (
    id,
    name,
    format,
    levels,
    qualifiers_count,
    current_state,
    category_id,
    order_index
)
SELECT
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    COALESCE(MAX(order_index), -1) + 1
FROM rounds
WHERE category_id = $6
RETURNING id, name, format, levels, qualifiers_count, category_id, order_index, current_state
`

type CreateRoundParams struct {
	Name            sql.NullString
	Format          int32
	Levels          sql.NullString
	QualifiersCount int32
	CurrentState    RoundState
	CategoryID      uuid.UUID
}

func (q *Queries) CreateRound(ctx context.Context, arg CreateRoundParams) (Round, error) {
	row := q.db.QueryRowContext(ctx, createRound,
		arg.Name,
		arg.Format,
		arg.Levels,
		arg.QualifiersCount,
		arg.CurrentState,
		arg.CategoryID,
	)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Format,
		&i.Levels,
		&i.QualifiersCount,
		&i.CategoryID,
		&i.OrderIndex,
		&i.CurrentState,
	)
	return i, err
}

const deleteRound = `-- name: DeleteRound :exec
DELETE FROM rounds
WHERE id = $1
`

func (q *Queries) DeleteRound(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRound, id)
	return err
}

const finishRound = `-- name: FinishRound :exec
UPDATE rounds
SET current_state = 'finished'
WHERE id = $1 AND current_state = 'in_progress'
`

func (q *Queries) FinishRound(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, finishRound, id)
	return err
}

const getRound = `-- name: GetRound :one
SELECT id, name, format, levels, qualifiers_count, category_id, order_index, current_state
FROM rounds
WHERE id = $1
`

func (q *Queries) GetRound(ctx context.Context, id uuid.UUID) (Round, error) {
	row := q.db.QueryRowContext(ctx, getRound, id)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Format,
		&i.Levels,
		&i.QualifiersCount,
		&i.CategoryID,
		&i.OrderIndex,
		&i.CurrentState,
	)
	return i, err
}

const listRounds = `-- name: ListRounds :many
SELECT id, name, format, levels, qualifiers_count, category_id, order_index, current_state
FROM rounds
WHERE category_id = $1
ORDER BY order_index ASC
`

func (q *Queries) ListRounds(ctx context.Context, categoryID uuid.UUID) ([]Round, error) {
	rows, err := q.db.QueryContext(ctx, listRounds, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Round
	for rows.Next() {
		var i Round
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Format,
			&i.Levels,
			&i.QualifiersCount,
			&i.CategoryID,
			&i.OrderIndex,
			&i.CurrentState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pauseRound = `-- name: PauseRound :exec
UPDATE rounds
SET current_state = 'paused'
WHERE id = $1 AND current_state = 'in_progress'
`

func (q *Queries) PauseRound(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, pauseRound, id)
	return err
}

const resumeRound = `-- name: ResumeRound :exec
UPDATE rounds
SET current_state = 'in_progress'
WHERE id = $1 AND (current_state = 'paused' OR current_state = 'finished')
`

func (q *Queries) ResumeRound(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, resumeRound, id)
	return err
}

const startRound = `-- name: StartRound :exec
UPDATE rounds
SET current_state = 'in_progress'
WHERE id = $1 AND current_state = 'not_started'
`

func (q *Queries) StartRound(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, startRound, id)
	return err
}

const updateRound = `-- name: UpdateRound :one
UPDATE rounds
SET
    name = COALESCE($2, name),
    format = COALESCE($3, format),
    levels = COALESCE($4, levels),
    qualifiers_count = COALESCE($5, qualifiers_count),
    current_state = COALESCE($6, current_state),
    category_id = COALESCE($7, category_id),
    order_index = COALESCE($8, order_index)
WHERE id = $1
RETURNING id, name, format, levels, qualifiers_count, category_id, order_index, current_state
`

type UpdateRoundParams struct {
	ID              uuid.UUID
	Name            sql.NullString
	Format          sql.NullInt32
	Levels          sql.NullString
	QualifiersCount sql.NullInt32
	CurrentState    NullRoundState
	CategoryId      uuid.NullUUID
	OrderIndex      sql.NullInt32
}

func (q *Queries) UpdateRound(ctx context.Context, arg UpdateRoundParams) (Round, error) {
	row := q.db.QueryRowContext(ctx, updateRound,
		arg.ID,
		arg.Name,
		arg.Format,
		arg.Levels,
		arg.QualifiersCount,
		arg.CurrentState,
		arg.CategoryId,
		arg.OrderIndex,
	)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Format,
		&i.Levels,
		&i.QualifiersCount,
		&i.CategoryID,
		&i.OrderIndex,
		&i.CurrentState,
	)
	return i, err
}
