// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rounds_players.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addPlayerToRound = `-- name: AddPlayerToRound :exec
INSERT INTO rounds_players (round_id, player_id, order_index)
SELECT
    $1,
    $2,
    COALESCE(MAX(order_index), -1) + 1
FROM rounds_players
WHERE round_id = $1
ON CONFLICT (round_id, player_id) DO NOTHING
`

type AddPlayerToRoundParams struct {
	RoundID  uuid.UUID
	PlayerID uuid.UUID
}

func (q *Queries) AddPlayerToRound(ctx context.Context, arg AddPlayerToRoundParams) error {
	_, err := q.db.ExecContext(ctx, addPlayerToRound, arg.RoundID, arg.PlayerID)
	return err
}

const addPlayersToRoundBulk = `-- name: AddPlayersToRoundBulk :exec
INSERT INTO rounds_players (round_id, player_id, order_index)
SELECT
  $1::uuid        AS round_id,
  unnest($2::uuid[]) AS player_id,
  generate_series(
    $3::int,
    ($3 + array_length($2, 1) - 1)::int
  ) AS order_index
`

type AddPlayersToRoundBulkParams struct {
	RoundID   uuid.UUID
	PlayerIds []uuid.UUID
	OrderBase int32
}

func (q *Queries) AddPlayersToRoundBulk(ctx context.Context, arg AddPlayersToRoundBulkParams) error {
	_, err := q.db.ExecContext(ctx, addPlayersToRoundBulk, arg.RoundID, pq.Array(arg.PlayerIds), arg.OrderBase)
	return err
}

const getMaxOrderIndexInRound = `-- name: GetMaxOrderIndexInRound :one
SELECT COALESCE(MAX(order_index), 0)
FROM rounds_players
WHERE round_id = $1
FOR UPDATE
`

func (q *Queries) GetMaxOrderIndexInRound(ctx context.Context, roundID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxOrderIndexInRound, roundID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const listPlayersInRound = `-- name: ListPlayersInRound :many
SELECT p.id, p.nickname, p.name, p.team_name, p.country_code, p.city, p.profile_picture_url, p.created_at, p.modified_at
FROM players p
JOIN rounds_players cp ON p.id = cp.player_id
WHERE cp.round_id = $1
`

func (q *Queries) ListPlayersInRound(ctx context.Context, roundID uuid.UUID) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, listPlayersInRound, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Nickname,
			&i.Name,
			&i.TeamName,
			&i.CountryCode,
			&i.City,
			&i.ProfilePictureUrl,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePlayerFromRound = `-- name: RemovePlayerFromRound :exec
DELETE FROM rounds_players
WHERE round_id = $1 AND player_id = $2
`

type RemovePlayerFromRoundParams struct {
	RoundID  uuid.UUID
	PlayerID uuid.UUID
}

func (q *Queries) RemovePlayerFromRound(ctx context.Context, arg RemovePlayerFromRoundParams) error {
	_, err := q.db.ExecContext(ctx, removePlayerFromRound, arg.RoundID, arg.PlayerID)
	return err
}
