// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rounds_charts.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addChartToRound = `-- name: AddChartToRound :exec
INSERT INTO rounds_charts (round_id, chart_id)
VALUES ($1, $2)
ON CONFLICT (round_id, chart_id) DO NOTHING
`

type AddChartToRoundParams struct {
	RoundID uuid.UUID
	ChartID uuid.UUID
}

func (q *Queries) AddChartToRound(ctx context.Context, arg AddChartToRoundParams) error {
	_, err := q.db.ExecContext(ctx, addChartToRound, arg.RoundID, arg.ChartID)
	return err
}

const listChartsInRound = `-- name: ListChartsInRound :many
SELECT c.id, c.song_id, c.mode, c.level, c.player_count
FROM charts c
JOIN rounds_charts rc ON c.id = rc.chart_id
WHERE rc.round_id = $1
ORDER BY rc.chart_id ASC
`

func (q *Queries) ListChartsInRound(ctx context.Context, roundID uuid.UUID) ([]Chart, error) {
	rows, err := q.db.QueryContext(ctx, listChartsInRound, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chart
	for rows.Next() {
		var i Chart
		if err := rows.Scan(
			&i.ID,
			&i.SongID,
			&i.Mode,
			&i.Level,
			&i.PlayerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeChartFromRound = `-- name: RemoveChartFromRound :exec
DELETE FROM rounds_charts
WHERE round_id = $1 AND chart_id = $2
`

type RemoveChartFromRoundParams struct {
	RoundID uuid.UUID
	ChartID uuid.UUID
}

func (q *Queries) RemoveChartFromRound(ctx context.Context, arg RemoveChartFromRoundParams) error {
	_, err := q.db.ExecContext(ctx, removeChartFromRound, arg.RoundID, arg.ChartID)
	return err
}
