// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scores.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createScore = `-- name: CreateScore :one
INSERT INTO scores (
    id,
    round_id,
    player_id,
    chart_id,
    score,
    perfect,
    great,
    good,
    bad,
    miss,
    max_combo,
    kcal,
    grade,
    stage_pass,
    video_url
) VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    COALESCE($5, 0),
    COALESCE($6, 0),
    COALESCE($7, 0),
    COALESCE($8, 0),
    COALESCE($9, 0),
    COALESCE($10, 0),
    COALESCE($11, 0),
    COALESCE($12::grade, 'F'::grade),
    COALESCE($13, false),
    COALESCE($14, '')
)
RETURNING id, round_id, player_id, chart_id, score, perfect, great, good, bad, miss, max_combo, kcal, grade, stage_pass, video_url
`

type CreateScoreParams struct {
	RoundID   uuid.UUID
	PlayerID  uuid.UUID
	ChartID   uuid.UUID
	Score     int32
	Perfect   interface{}
	Great     interface{}
	Good      interface{}
	Bad       interface{}
	Miss      interface{}
	MaxCombo  interface{}
	Kcal      interface{}
	Grade     NullGrade
	StagePass interface{}
	VideoUrl  interface{}
}

func (q *Queries) CreateScore(ctx context.Context, arg CreateScoreParams) (Score, error) {
	row := q.db.QueryRowContext(ctx, createScore,
		arg.RoundID,
		arg.PlayerID,
		arg.ChartID,
		arg.Score,
		arg.Perfect,
		arg.Great,
		arg.Good,
		arg.Bad,
		arg.Miss,
		arg.MaxCombo,
		arg.Kcal,
		arg.Grade,
		arg.StagePass,
		arg.VideoUrl,
	)
	var i Score
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.PlayerID,
		&i.ChartID,
		&i.Score,
		&i.Perfect,
		&i.Great,
		&i.Good,
		&i.Bad,
		&i.Miss,
		&i.MaxCombo,
		&i.Kcal,
		&i.Grade,
		&i.StagePass,
		&i.VideoUrl,
	)
	return i, err
}

const deleteScore = `-- name: DeleteScore :exec
DELETE FROM scores WHERE id = $1
`

func (q *Queries) DeleteScore(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteScore, id)
	return err
}

const getScore = `-- name: GetScore :one
SELECT id, round_id, player_id, chart_id, score, perfect, great, good, bad, miss, max_combo, kcal, grade, stage_pass, video_url FROM scores WHERE id = $1
`

func (q *Queries) GetScore(ctx context.Context, id uuid.UUID) (Score, error) {
	row := q.db.QueryRowContext(ctx, getScore, id)
	var i Score
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.PlayerID,
		&i.ChartID,
		&i.Score,
		&i.Perfect,
		&i.Great,
		&i.Good,
		&i.Bad,
		&i.Miss,
		&i.MaxCombo,
		&i.Kcal,
		&i.Grade,
		&i.StagePass,
		&i.VideoUrl,
	)
	return i, err
}

const listScores = `-- name: ListScores :many
SELECT id, round_id, player_id, chart_id, score, perfect, great, good, bad, miss, max_combo, kcal, grade, stage_pass, video_url FROM scores WHERE round_id = $1 ORDER BY score DESC
`

func (q *Queries) ListScores(ctx context.Context, roundid uuid.UUID) ([]Score, error) {
	rows, err := q.db.QueryContext(ctx, listScores, roundid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Score
	for rows.Next() {
		var i Score
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.PlayerID,
			&i.ChartID,
			&i.Score,
			&i.Perfect,
			&i.Great,
			&i.Good,
			&i.Bad,
			&i.Miss,
			&i.MaxCombo,
			&i.Kcal,
			&i.Grade,
			&i.StagePass,
			&i.VideoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScore = `-- name: UpdateScore :one
UPDATE scores SET
    score = COALESCE($1, score),
    perfect = COALESCE($2, perfect),
    great = COALESCE($3, great),
    good = COALESCE($4, good),
    bad = COALESCE($5, bad),
    miss = COALESCE($6, miss),
    max_combo = COALESCE($7, max_combo),
    kcal = COALESCE($8, kcal),
    grade = COALESCE($9::grade, grade),
    stage_pass = COALESCE($10, stage_pass),
    video_url = COALESCE($11, video_url)
WHERE id = $12
RETURNING id, round_id, player_id, chart_id, score, perfect, great, good, bad, miss, max_combo, kcal, grade, stage_pass, video_url
`

type UpdateScoreParams struct {
	Score     sql.NullInt32
	Perfect   sql.NullInt32
	Great     sql.NullInt32
	Good      sql.NullInt32
	Bad       sql.NullInt32
	Miss      sql.NullInt32
	MaxCombo  sql.NullInt32
	Kcal      sql.NullFloat64
	Grade     NullGrade
	StagePass sql.NullBool
	VideoUrl  sql.NullString
	ID        uuid.UUID
}

func (q *Queries) UpdateScore(ctx context.Context, arg UpdateScoreParams) (Score, error) {
	row := q.db.QueryRowContext(ctx, updateScore,
		arg.Score,
		arg.Perfect,
		arg.Great,
		arg.Good,
		arg.Bad,
		arg.Miss,
		arg.MaxCombo,
		arg.Kcal,
		arg.Grade,
		arg.StagePass,
		arg.VideoUrl,
		arg.ID,
	)
	var i Score
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.PlayerID,
		&i.ChartID,
		&i.Score,
		&i.Perfect,
		&i.Great,
		&i.Good,
		&i.Bad,
		&i.Miss,
		&i.MaxCombo,
		&i.Kcal,
		&i.Grade,
		&i.StagePass,
		&i.VideoUrl,
	)
	return i, err
}
