// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: songs.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createSong = `-- name: CreateSong :one
INSERT INTO songs (
    id,
    name,
    title_url
)
VALUES (
    gen_random_uuid(),
    $1,
    $2
)
RETURNING id, name, title_url
`

type CreateSongParams struct {
	Name     string
	TitleUrl sql.NullString
}

func (q *Queries) CreateSong(ctx context.Context, arg CreateSongParams) (Song, error) {
	row := q.db.QueryRowContext(ctx, createSong, arg.Name, arg.TitleUrl)
	var i Song
	err := row.Scan(&i.ID, &i.Name, &i.TitleUrl)
	return i, err
}

const deleteSong = `-- name: DeleteSong :exec
DELETE FROM songs
WHERE id = $1
`

func (q *Queries) DeleteSong(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSong, id)
	return err
}

const getSong = `-- name: GetSong :one
SELECT id, name, title_url
FROM songs
WHERE id = $1
`

func (q *Queries) GetSong(ctx context.Context, id uuid.UUID) (Song, error) {
	row := q.db.QueryRowContext(ctx, getSong, id)
	var i Song
	err := row.Scan(&i.ID, &i.Name, &i.TitleUrl)
	return i, err
}

const listSongs = `-- name: ListSongs :many
SELECT id, name, title_url
FROM songs
ORDER BY name ASC
`

func (q *Queries) ListSongs(ctx context.Context) ([]Song, error) {
	rows, err := q.db.QueryContext(ctx, listSongs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Song
	for rows.Next() {
		var i Song
		if err := rows.Scan(&i.ID, &i.Name, &i.TitleUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSong = `-- name: UpdateSong :one
UPDATE songs
SET
    name = COALESCE($2, name),
    title_url = COALESCE($3, title_url)
WHERE id = $1
RETURNING id, name, title_url
`

type UpdateSongParams struct {
	ID       uuid.UUID
	Name     sql.NullString
	TitleUrl sql.NullString
}

func (q *Queries) UpdateSong(ctx context.Context, arg UpdateSongParams) (Song, error) {
	row := q.db.QueryRowContext(ctx, updateSong, arg.ID, arg.Name, arg.TitleUrl)
	var i Song
	err := row.Scan(&i.ID, &i.Name, &i.TitleUrl)
	return i, err
}
