// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tournaments.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createTournament = `-- name: CreateTournament :one
INSERT INTO tournaments (id, name, location, start_date)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3
)
RETURNING id, name, location, start_date
`

type CreateTournamentParams struct {
	Name      string
	Location  sql.NullString
	StartDate sql.NullTime
}

func (q *Queries) CreateTournament(ctx context.Context, arg CreateTournamentParams) (Tournament, error) {
	row := q.db.QueryRowContext(ctx, createTournament, arg.Name, arg.Location, arg.StartDate)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.StartDate,
	)
	return i, err
}

const deleteTournament = `-- name: DeleteTournament :exec
DELETE FROM tournaments
WHERE id = $1
`

func (q *Queries) DeleteTournament(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTournament, id)
	return err
}

const getTournament = `-- name: GetTournament :one
SELECT id, name, location, start_date
FROM tournaments
WHERE id = $1
`

func (q *Queries) GetTournament(ctx context.Context, id uuid.UUID) (Tournament, error) {
	row := q.db.QueryRowContext(ctx, getTournament, id)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.StartDate,
	)
	return i, err
}

const listTournaments = `-- name: ListTournaments :many
SELECT id, name, location, start_date
FROM tournaments
ORDER BY start_date DESC
`

func (q *Queries) ListTournaments(ctx context.Context) ([]Tournament, error) {
	rows, err := q.db.QueryContext(ctx, listTournaments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tournament
	for rows.Next() {
		var i Tournament
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.StartDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTournament = `-- name: UpdateTournament :one
UPDATE tournaments
SET
    name = COALESCE($2, name),
    location = COALESCE($3, location),
    start_date = COALESCE($4, start_date)
WHERE id = $1
RETURNING id, name, location, start_date
`

type UpdateTournamentParams struct {
	ID        uuid.UUID
	Name      sql.NullString
	Location  sql.NullString
	StartDate sql.NullTime
}

func (q *Queries) UpdateTournament(ctx context.Context, arg UpdateTournamentParams) (Tournament, error) {
	row := q.db.QueryRowContext(ctx, updateTournament,
		arg.ID,
		arg.Name,
		arg.Location,
		arg.StartDate,
	)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.StartDate,
	)
	return i, err
}
